/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liubs_findinstances_jvmti_InstancesOfClass */

#ifndef _Included_com_liubs_findinstances_jvmti_InstancesOfClass
#define _Included_com_liubs_findinstances_jvmti_InstancesOfClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liubs_findinstances_jvmti_InstancesOfClass
 * Method:    getInstances
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_liubs_findinstances_jvmti_InstancesOfClass_getInstances
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
